---
title: "Exercise 7"
output:
  html_document:
    toc: true
    theme: united
    highlight: pygments
    number_sections: false
---
```{r message=FALSE, echo=FALSE}
library(zoo)
```

###Q1
```{r}
sheep.zoo = read.zoo("Sheep.dat")

sheep.ts = as.ts(sheep.zoo)
plot(sheep.ts)
acf(sheep.ts)

sheepd.ts = diff(sheep.ts)
plot(sheepd.ts)
acf(sheepd.ts,lag=50)

sheep.ar1.arima = arima(sheep.ts, c(1,1,0))
sheep.ar2.arima = arima(sheep.ts, c(2,1,0))
sheep.ar3.arima = arima(sheep.ts, c(3,1,0))
sheep.ma1.arima = arima(sheep.ts, c(0,1,1))
sheep.ma2.arima = arima(sheep.ts, c(0,1,2))
sheep.ma3.arima = arima(sheep.ts, c(0,1,3))

sheep.ar1.arima
tsdiag(sheep.ar1.arima, gof.lag = 24)

sheep.ar2.arima
tsdiag(sheep.ar2.arima, gof.lag = 24)

sheep.ar3.arima
tsdiag(sheep.ar3.arima, gof.lag = 24)

sheep.ma1.arima
tsdiag(sheep.ma1.arima, gof.lag = 24)

sheep.ma2.arima
tsdiag(sheep.ma2.arima, gof.lag = 24)

sheep.ma3.arima
tsdiag(sheep.ma3.arima, gof.lag = 24)

```

###Q2
```{r}
canada.zoo <- read.zoo("Canadata.dat", 
                        index.column = 2:3, 
                        FUN = function(year, month){ as.yearmon(paste(year, month, sep = "-"))})
canada.ts = as.ts(canada.zoo)
plot(canada.ts)
lcanada.ts = log(canada.ts)
plot(lcanada.ts)
acf(lcanada.ts)

acf(diff(lcanada.ts, lag = 12))
acf(diff(diff(lcanada.ts),lag = 12))

lcanada.arima = arima(lcanada.ts, order = c(0,1,1), seasonal = list(order=c(0,1,1), period=12))

lcanada.arima

tsdiag(lcanada.arima)
```

The fitted model is:

$$ T_t = T_{t-1} + Y_{t-12} - Y_{t-13} + \epsilon_t `r lcanada.arima$coef[1]` \epsilon_{t-1} `r lcanada.arima$coef[2]` \epsilon_{t-12} + \text{ TODO } \epsilon_{t-13}$$